apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: koog-ai
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2  # AWS EBS
  # storageClassName: standard  # GCP
  # storageClassName: managed-premium  # Azure
