apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "koog-ai-assistant.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "koog-ai-assistant.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.koogAi.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "koog-ai-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "koog-ai-assistant.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "koog-ai-assistant.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.security.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.koogAi.image.repository }}:{{ .Values.koogAi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.koogAi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.koogAi.service.targetPort }}
              protocol: TCP
          env:
            - name: OLLAMA_HOST
              value: {{ .Values.config.ollamaHost | quote }}
            - name: WEB_PORT
              value: {{ .Values.config.webPort | quote }}
            - name: MODEL_CACHE_TTL
              value: {{ .Values.config.modelCacheTtl | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
            - name: DEBUG
              value: {{ .Values.config.debug | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.config.environment | quote }}
            - name: MAX_CONCURRENT_REQUESTS
              value: {{ .Values.config.maxConcurrentRequests | quote }}
            - name: REQUEST_TIMEOUT
              value: {{ .Values.config.requestTimeout | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
          resources:
            {{- toYaml .Values.koogAi.resources | nindent 12 }}
          {{- with .Values.koogAi.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.koogAi.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.koogAi.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
